/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/Prod//nihii': {
    /**
     * /Prod//nihii
     * @description **Host**: http://ny652h2ixk.execute-api.eu-west-1.amazonaws.com
     */
    get: {
      parameters: {
        query?: {
          profession?: string;
          version?: string;
          amount?: number;
        };
      };
      responses: {
        200: {
          headers: {
            'x-amz-apigw-id'?: string;
            'x-amz-cf-id'?: string;
            'x-amz-cf-pop'?: string;
            'x-amzn-requestid'?: string;
            'x-amzn-trace-id'?: string;
            'x-cache'?: string;
          };
          content: {
            'application/json': {
              nihii: string[];
            };
          };
        };
      };
    };
  };
  '/Prod//niscode': {
    /**
     * /Prod//niscode
     * @description **Host**: http://ny652h2ixk.execute-api.eu-west-1.amazonaws.com
     */
    get: {
      parameters: {
        query?: {
          postalcode?: string;
        };
      };
      responses: {
        200: {
          headers: {
            'x-amz-apigw-id'?: string;
            'x-amz-cf-id'?: string;
            'x-amz-cf-pop'?: string;
            'x-amzn-requestid'?: string;
            'x-amzn-trace-id'?: string;
            'x-cache'?: string;
          };
          content: {
            'application/json': {
              NIS_code: string | string[];
            };
          };
        };
      };
    };
  };
  '/Prod//pv': {
    /**
     * /Prod//pv
     * @description **Host**: http://ny652h2ixk.execute-api.eu-west-1.amazonaws.com
     */
    get: {
      parameters: {
        query?: {
          year?: string;
          amount?: number;
        };
      };
      responses: {
        200: {
          headers: {
            'x-amz-apigw-id'?: string;
            'x-amz-cf-id'?: string;
            'x-amz-cf-pop'?: string;
            'x-amzn-requestid'?: string;
            'x-amzn-trace-id'?: string;
            'x-cache'?: string;
          };
          content: {
            'application/json': {
              pvs: string[];
            };
          };
        };
      };
    };
  };
  '/Prod//riziv': {
    /**
     * /Prod//riziv
     * @description **Host**: http://ny652h2ixk.execute-api.eu-west-1.amazonaws.com
     */
    get: {
      parameters: {
        query?: {
          profession?: string;
          amount?: number;
        };
      };
      responses: {
        200: {
          headers: {
            'x-amz-apigw-id'?: string;
            'x-amz-cf-id'?: string;
            'x-amz-cf-pop'?: string;
            'x-amzn-requestid'?: string;
            'x-amzn-trace-id'?: string;
            'x-cache'?: string;
          };
          content: {
            'application/json': {
              riziv: string[];
            };
          };
        };
      };
    };
  };
  '/Prod//insz': {
    /**
     * /Prod//insz
     * @description **Host**: http://ny652h2ixk.execute-api.eu-west-1.amazonaws.com
     */
    get: {
      parameters: {
        query?: {
          date?: string;
          amount?: number;
          info?: string;
          adult?: string;
        };
      };
      responses: {
        200: {
          headers: {
            'x-amz-apigw-id'?: string;
            'x-amz-cf-id'?: string;
            'x-amz-cf-pop'?: string;
            'x-amzn-requestid'?: string;
            'x-amzn-trace-id'?: string;
            'x-cache'?: string;
          };
          content: {
            'application/json': {
              inszs: string[];
            };
          };
        };
      };
    };
  };
  '/Prod//uuid': {
    /**
     * /Prod//uuid
     * @description **Host**: http://ny652h2ixk.execute-api.eu-west-1.amazonaws.com
     */
    get: {
      parameters: {
        query?: {
          version?: number;
          amount?: number;
        };
      };
      responses: {
        200: {
          headers: {
            'x-amz-apigw-id'?: string;
            'x-amz-cf-id'?: string;
            'x-amz-cf-pop'?: string;
            'x-amzn-requestid'?: string;
            'x-amzn-trace-id'?: string;
            'x-cache'?: string;
          };
          content: {
            'application/json': {
              uuids: string[];
            };
          };
        };
      };
    };
  };
  '/Prod//plates': {
    /**
     * /Prod//plates
     * @description **Host**: http://ny652h2ixk.execute-api.eu-west-1.amazonaws.com
     */
    get: {
      parameters: {
        query?: {
          plates?: string;
          amount?: number;
        };
      };
      responses: {
        200: {
          headers: {
            'x-amz-apigw-id'?: string;
            'x-amz-cf-id'?: string;
            'x-amz-cf-pop'?: string;
            'x-amzn-requestid'?: string;
            'x-amzn-trace-id'?: string;
            'x-cache'?: string;
          };
          content: {
            'application/json': {
              plates: string[];
            };
          };
        };
      };
    };
  };
  '/Prod//lorem': {
    /**
     * /Prod//lorem
     * @description **Host**: http://ny652h2ixk.execute-api.eu-west-1.amazonaws.com
     */
    get: {
      parameters: {
        query?: {
          lettersOnly?: string;
          length?: string;
        };
      };
      responses: {
        200: {
          headers: {
            'x-amz-apigw-id'?: string;
            'x-amz-cf-id'?: string;
            'x-amz-cf-pop'?: string;
            'x-amzn-requestid'?: string;
            'x-amzn-trace-id'?: string;
            'x-cache'?: string;
          };
          content: {
            'application/json': {
              lorem: string;
            };
          };
        };
      };
    };
  };
  '/Prod//telephone': {
    /**
     * /Prod//telephone
     * @description **Host**: http://ny652h2ixk.execute-api.eu-west-1.amazonaws.com
     */
    get: {
      parameters: {
        query?: {
          country?: string;
          amount?: number;
        };
      };
      responses: {
        200: {
          headers: {
            'x-amz-apigw-id'?: string;
            'x-amz-cf-id'?: string;
            'x-amz-cf-pop'?: string;
            'x-amzn-requestid'?: string;
            'x-amzn-trace-id'?: string;
            'x-cache'?: string;
          };
          content: {
            'application/json': {
              phoneNumber: string[];
            };
          };
        };
      };
    };
  };
  '/Prod//unix': {
    /**
     * /Prod//unix
     * @description **Host**: http://ny652h2ixk.execute-api.eu-west-1.amazonaws.com
     */
    get: {
      parameters: {
        query?: {
          date?: string;
          timestamp?: string;
        };
      };
      responses: {
        200: {
          headers: {
            'x-amz-apigw-id'?: string;
            'x-amz-cf-id'?: string;
            'x-amz-cf-pop'?: string;
            'x-amzn-requestid'?: string;
            'x-amzn-trace-id'?: string;
            'x-cache'?: string;
          };
          content: {
            'application/json': {
              unix: string[];
            };
          };
        };
      };
    };
  };
  '/Prod//polis': {
    /**
     * /Prod//polis
     * @description **Host**: http://ny652h2ixk.execute-api.eu-west-1.amazonaws.com
     */
    get: {
      parameters: {
        query?: {
          company?: string;
          amount?: number;
        };
      };
      responses: {
        200: {
          headers: {
            'x-amz-apigw-id'?: string;
            'x-amz-cf-id'?: string;
            'x-amz-cf-pop'?: string;
            'x-amzn-requestid'?: string;
            'x-amzn-trace-id'?: string;
            'x-cache'?: string;
          };
          content: {
            'application/json': {
              polisnummer: string[];
            };
          };
        };
      };
    };
  };
  '/Prod//iban': {
    /**
     * /Prod//iban
     * @description **Host**: http://ny652h2ixk.execute-api.eu-west-1.amazonaws.com
     */
    get: {
      parameters: {
        query?: {
          iban?: string;
          amount?: number;
        };
      };
      responses: {
        200: {
          headers: {
            'x-amz-apigw-id'?: string;
            'x-amz-cf-id'?: string;
            'x-amz-cf-pop'?: string;
            'x-amzn-requestid'?: string;
            'x-amzn-trace-id'?: string;
            'x-cache'?: string;
          };
          content: {
            'application/json': {
              iban: string[];
            };
          };
        };
      };
    };
  };
  '/Prod//prepare': {
    /**
     * /Prod//prepare
     * @description **Host**: http://ny652h2ixk.execute-api.eu-west-1.amazonaws.com
     */
    get: {
      responses: {
        200: {
          headers: {
            'x-amz-apigw-id'?: string;
            'x-amz-cf-id'?: string;
            'x-amz-cf-pop'?: string;
            'x-amzn-requestid'?: string;
            'x-amzn-trace-id'?: string;
            'x-cache'?: string;
          };
          content: {
            'application/json': {
              polisnummer: string[];
              nihii: string[];
              riziv: string[];
              plates: string[];
              phoneNumber: string[];
              iban: string[];
            };
          };
        };
      };
    };
  };
  '/Prod//bis': {
    /**
     * /Prod//bis
     * @description **Host**: http://ny652h2ixk.execute-api.eu-west-1.amazonaws.com
     */
    get: {
      parameters: {
        query?: {
          isGenderKnown?: boolean;
          isBirthdateKnown?: boolean;
          date?: string;
          amount?: number;
        };
      };
      responses: {
        200: {
          headers: {
            'x-amz-apigw-id'?: string;
            'x-amz-cf-id'?: string;
            'x-amz-cf-pop'?: string;
            'x-amzn-requestid'?: string;
            'x-amzn-trace-id'?: string;
            'x-cache'?: string;
          };
          content: {
            'application/json': {
              bis: string[];
            };
          };
        };
      };
    };
  };
  '/Prod//bsn': {
    /**
     * /Prod//bsn
     * @description **Host**: http://ny652h2ixk.execute-api.eu-west-1.amazonaws.com
     */
    get: {
      parameters: {
        query?: {
          amount?: number;
        };
      };
      responses: {
        200: {
          headers: {
            'x-amz-apigw-id'?: string;
            'x-amz-cf-id'?: string;
            'x-amz-cf-pop'?: string;
            'x-amzn-requestid'?: string;
            'x-amzn-trace-id'?: string;
            'x-cache'?: string;
          };
          content: {
            'application/json': {
              bsns: string[];
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
